// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniversityRegistrationSystem.Data;

#nullable disable

namespace UniversityRegistrationSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniversityRegistrationSystem.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<int>("DeptId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("CourseId");

                    b.HasIndex("DeptId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Credits = 4,
                            DeptId = 1,
                            Title = "Algorithms"
                        },
                        new
                        {
                            CourseId = 2,
                            Credits = 3,
                            DeptId = 1,
                            Title = "Data Structures"
                        },
                        new
                        {
                            CourseId = 3,
                            Credits = 4,
                            DeptId = 2,
                            Title = "Calculus I"
                        },
                        new
                        {
                            CourseId = 4,
                            Credits = 4,
                            DeptId = 3,
                            Title = "Physics I"
                        });
                });

            modelBuilder.Entity("UniversityRegistrationSystem.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            DeptName = "Computer Science"
                        },
                        new
                        {
                            DeptId = 2,
                            DeptName = "Mathematics"
                        },
                        new
                        {
                            DeptId = 3,
                            DeptName = "Physics"
                        });
                });

            modelBuilder.Entity("UniversityRegistrationSystem.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnrolId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("EnrolId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrolId = 1,
                            CourseId = 1,
                            Semester = "Fall",
                            StudentId = 1,
                            Year = 2023
                        },
                        new
                        {
                            EnrolId = 2,
                            CourseId = 2,
                            Semester = "Spring",
                            StudentId = 1,
                            Year = 2024
                        },
                        new
                        {
                            EnrolId = 3,
                            CourseId = 3,
                            Semester = "Fall",
                            StudentId = 2,
                            Year = 2023
                        },
                        new
                        {
                            EnrolId = 4,
                            CourseId = 1,
                            Semester = "Spring",
                            StudentId = 3,
                            Year = 2024
                        },
                        new
                        {
                            EnrolId = 5,
                            CourseId = 4,
                            Semester = "Fall",
                            StudentId = 4,
                            Year = 2023
                        });
                });

            modelBuilder.Entity("UniversityRegistrationSystem.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GradeId"));

                    b.Property<int>("EnrolId")
                        .HasColumnType("integer");

                    b.Property<string>("LetterGrade")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<decimal>("NumericGrade")
                        .HasColumnType("numeric");

                    b.HasKey("GradeId");

                    b.HasIndex("EnrolId")
                        .IsUnique();

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            EnrolId = 1,
                            LetterGrade = "A",
                            NumericGrade = 93.5m
                        },
                        new
                        {
                            GradeId = 2,
                            EnrolId = 2,
                            LetterGrade = "B+",
                            NumericGrade = 88.0m
                        },
                        new
                        {
                            GradeId = 3,
                            EnrolId = 3,
                            LetterGrade = "C",
                            NumericGrade = 76.0m
                        },
                        new
                        {
                            GradeId = 4,
                            EnrolId = 4,
                            LetterGrade = "A-",
                            NumericGrade = 91.0m
                        },
                        new
                        {
                            GradeId = 5,
                            EnrolId = 5,
                            LetterGrade = "B-",
                            NumericGrade = 82.5m
                        });
                });

            modelBuilder.Entity("UniversityRegistrationSystem.Models.Instructor", b =>
                {
                    b.Property<int>("InstId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InstId"));

                    b.Property<int>("DeptId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("InstId");

                    b.HasIndex("DeptId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            InstId = 1,
                            DeptId = 1,
                            Name = "Dr. Susan Smith"
                        },
                        new
                        {
                            InstId = 2,
                            DeptId = 2,
                            Name = "Dr. Linh Nguyen"
                        },
                        new
                        {
                            InstId = 3,
                            DeptId = 3,
                            Name = "Dr. Raj Patel"
                        });
                });

            modelBuilder.Entity("UniversityRegistrationSystem.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("MajorId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("StudentId");

                    b.HasIndex("MajorId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "alice.johnson@example.com",
                            MajorId = 1,
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            StudentId = 2,
                            Email = "bob.martinez@example.com",
                            MajorId = 2,
                            Name = "Bob Martinez"
                        },
                        new
                        {
                            StudentId = 3,
                            Email = "carol.lee@example.com",
                            MajorId = 1,
                            Name = "Carol Lee"
                        },
                        new
                        {
                            StudentId = 4,
                            Email = "dave.kim@example.com",
                            MajorId = 3,
                            Name = "Dave Kim"
                        });
                });

            modelBuilder.Entity("UniversityRegistrationSystem.Models.Course", b =>
                {
                    b.HasOne("UniversityRegistrationSystem.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UniversityRegistrationSystem.Models.Enrollment", b =>
                {
                    b.HasOne("UniversityRegistrationSystem.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityRegistrationSystem.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversityRegistrationSystem.Models.Grade", b =>
                {
                    b.HasOne("UniversityRegistrationSystem.Models.Enrollment", "Enrollment")
                        .WithOne("Grade")
                        .HasForeignKey("UniversityRegistrationSystem.Models.Grade", "EnrolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("UniversityRegistrationSystem.Models.Instructor", b =>
                {
                    b.HasOne("UniversityRegistrationSystem.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UniversityRegistrationSystem.Models.Student", b =>
                {
                    b.HasOne("UniversityRegistrationSystem.Models.Department", "Major")
                        .WithMany("Students")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("UniversityRegistrationSystem.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("UniversityRegistrationSystem.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("UniversityRegistrationSystem.Models.Enrollment", b =>
                {
                    b.Navigation("Grade");
                });

            modelBuilder.Entity("UniversityRegistrationSystem.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
